#!name=芒果🥭TV
#!desc=解锁芒果SVIP

[Script]

mgtv = type=http-response,pattern=https://nuc.api.mgtv.com/GetUserInfo,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Yu9191/Rewrite/main/mgtv.js

mgtv = type=http-response,pattern=https://mobile-stream.api.mgtv.com/v1/video/source,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Yu9191/Rewrite/main/mgtv.js

mgtv1 = type=http-request,pattern=^http[s]?:\/\/mobile\.api\.mgtv\.com\/v[0-9]\/(playlist|video\/album|video\/relative|video\/list).*$,requires-body=0,max-size=0,script-path=https://raw.githubusercontent.com/Yu9191/Rewrite/main/mgtv1.js

MGTV = type=http-request,pattern=https://mobile-stream.api.mgtv.com/v1/video/source?,requires-body=0,max-size=0,script-path=https://raw.githubusercontent.com/Yu9191/Rewrite/main/MGTV.js

[MITM]
hostname= %APPEND% *.mgtv.com
