#!name=芒果🥭TV-SVIP
#!desc=解锁芒果2023-12-15


[Script]
mgtv = type=http-response,pattern=https://nuc.api.mgtv.com/GetUserInfo,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Fromboy/conf/MGTV/mgtv.js
mgtv = type=http-response,pattern=https://mobile-stream.api.mgtv.com/v1/video/source,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/Fromboy/conf/MGTV/mgtv.js
mgtv1 = type=http-request,pattern=^http[s]?:\/\/mobile\.api\.mgtv\.com\/v[0-9]\/(playlist|video\/album|video\/relative|video\/list).*$,requires-body=0,max-size=0,script-path= https://raw.githubusercontent.com/Fromboy/conf/MGTV/mgtv1.js
MGTV = type=http-request,pattern=https://mobile-stream.api.mgtv.com/v1/video/source?,requires-body=0,max-size=0,script-path=https://raw.githubusercontent.com/Fromboy/conf/MGTV/MGTV.js
[MITM]
hostname= %APPEND% *.mgtv.com
